[[Xorg_xkbcomp]]
arch = "armv7l"
git-tree-sha1 = "ec649f93ec07ca06ccfd353a17b51aa4859ee001"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "eafdf7a4608e580d6b367b7dba4609bf850e5f0abdf98322e796aa2d3f06b6a6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+0/Xorg_xkbcomp.v1.4.2.arm-linux-gnueabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "ac565d9cc8bba64725b9581c06658aec8329809b"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "fdae128b7e2dec354ace99ddfce2fc048df5594e9f1a184ccd2c5c24f004fd11"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+0/Xorg_xkbcomp.v1.4.2.aarch64-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "i686"
git-tree-sha1 = "a26333c37c6fccdab6ddd745eb9f33a115c4497d"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "c4010ee6a1ac1c5f083406bf76f827173def73ad978af9c1f287030066d05693"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+0/Xorg_xkbcomp.v1.4.2.i686-linux-musl.tar.gz"
[[Xorg_xkbcomp]]
arch = "i686"
git-tree-sha1 = "b57859c1d90e476074c8177a428ae1fee26c0771"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "0c2f358f394373149fa1c7925a0d6daccb26e563656503f556b871ac2266cb55"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+0/Xorg_xkbcomp.v1.4.2.i686-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "280ddec16957ae2b387ce819fbe675d967a90039"
os = "freebsd"

    [[Xorg_xkbcomp.download]]
    sha256 = "cfb8bbd5ffba932f02e67e33ab3e6cccb1217712f34f12fb1ba80db4d1aedbe4"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+0/Xorg_xkbcomp.v1.4.2.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_xkbcomp]]
arch = "powerpc64le"
git-tree-sha1 = "c0995a89487e03da2d6df2457db78b7b49d2bccd"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "e4397fe0035fe27efb871653abf82966eeebe5cd558a2f9a26696b65717a5924"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+0/Xorg_xkbcomp.v1.4.2.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "armv7l"
git-tree-sha1 = "921f971c52f22a82c46ca5f6b9504598a7ecec24"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "c465b5be55f58b9a5e9af27b4cd30625bbd4b6e610e6b67e4bdeae328e594988"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+0/Xorg_xkbcomp.v1.4.2.arm-linux-musleabihf.tar.gz"
[[Xorg_xkbcomp]]
arch = "aarch64"
git-tree-sha1 = "ac834aadd35b5be0bff3a5d161abced4591f0e38"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "b7047f8ec49721178b3389e21d1d032c350712a19c7c70bbc357beb3ac3cd6c8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+0/Xorg_xkbcomp.v1.4.2.aarch64-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "21d340585ce628826a6691bdcaba5f3b517e3d5d"
libc = "glibc"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "2ddd2cab79775996d38c55acf7c07d8f90677a9f7b29a24212ecab1b3ce68c7e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+0/Xorg_xkbcomp.v1.4.2.x86_64-linux-gnu.tar.gz"
[[Xorg_xkbcomp]]
arch = "x86_64"
git-tree-sha1 = "9b1bf5b6f82680399d43b059a4a6fad4186ca057"
libc = "musl"
os = "linux"

    [[Xorg_xkbcomp.download]]
    sha256 = "1f51999b5c18ff87d09a3b58edcade19017d58bec482f316c37359bd67dbd4f1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xkbcomp_jll.jl/releases/download/Xorg_xkbcomp-v1.4.2+0/Xorg_xkbcomp.v1.4.2.x86_64-linux-musl.tar.gz"
